---
galaxy_info:
  author: Andrew Rothstein
  description: installs Apache Hadoop
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - hadoop
    - hdfs
    - yarn

dependencies:
  - role: andrewrothstein.unarchive-deps
    version: v1.0.10
  - role: andrewrothstein.java-oracle-jre
    version: v2.0.9
