---
# defaults file for java-oracle

# jre or jdk
java_oracle_prefix: jre

java_oracle_mirror: http://download.oracle.com/otn-pub/java/jdk
java_oracle_platform: linux-x64

# https://www.oracle.com/webfolder/s/digest/8u181checksum.html
# http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jre-8u181-linux-x64.tar.gz
# http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz

java_oracle_ver:
  major: 8
  minor: 0
  patch: 181
  post_patch: b13
  uuid: '96a7b8442fe848ef90c96a2fad6ed6d1'
  checksums:
    jre:
      'linux-x64': sha256:0b26c7fcfad20029e6e0989e678efcd4a81f0fe502a478b4972215533867de1b
    jdk:
      'linux-x64': sha256:1845567095bfbfebd42ed0d09397939796d05456290fb20a83c476ba09f991d3

java_oracle_parent_install_dir: /usr/local
java_oracle_timeout_seconds: 600
