---
- name: check for install..
  become: yes
  stat:
    path: '{{java_oracle_install_dir}}'
  changed_when: False
  register: java_oracle_binary
- when: not java_oracle_binary.stat.exists
  block:
    - name: download tgz...
      become: yes
      become_user: root
      get_url:
        headers:
          Cookie: oraclelicense=accept-securebackup-cookie
        url: '{{java_oracle_tgz_url}}'
        dest: /tmp/{{java_oracle_tgz}}
        checksum: '{{java_oracle_checksum}}'
        mode: 0644
        timeout: '{{java_oracle_timeout_seconds}}'
    - name: unarchive....
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{java_oracle_tgz}}
        dest: '{{java_oracle_parent_install_dir}}'
        creates: '{{java_oracle_install_dir}}'
  always:
    - name: cleanup
      become: yes
      become_user: root
      file:
        path: /tmp/{{java_oracle_tgz}}
        state: absent
- name: link....
  become: yes
  become_user: root
  file:
    src: '{{java_oracle_install_dir}}'
    dest: '{{java_oracle_link_dir}}'
    state: link

- name: add to default path and ease systemd integration...
  become: yes
  become_user: root
  with_items:
    - f: java-oracle.sh
      d: /etc/profile.d
    - f: java-oracle.env
      d: '{{java_oracle_install_dir}}'
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m|default("0644")}}'
